[project]
name = "yt-subtitle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "uvicorn>=0.34.3",
    "youtube-transcript-api>=1.1.0",
]
